--CRIAÇÃO DAS TABELAS--

CREATE TABLE TB_CLIENTE (
    ID_CLIENTE         		INT           		NOT NULL,
    ID_USUARIO         		INT           		NOT NULL,
    PRIMEIRO_NOME     	    VARCHAR(50)   	    NOT NULL,
    ULTIMO_NOME        	    VARCHAR(50)   	    NOT NULL,
    CPF                		VARCHAR(11)      	NOT NULL,
    SEXO               		VARCHAR(1),
    DATA_NASCIMENTO    	    DATE,

    PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE TB_CARTOES (
    ID_CARTAO          		INT           		NOT NULL,
    ID_CLIENTE         		INT           		NOT NULL,
    NOME_TITULAR       	    VARCHAR(100)  	NOT NULL,
    VALIDADE           		DATE          		NOT NULL,
    CVV                		VARCHAR(3)       	NOT NULL,
    NUMERO_CARTAO      	    VARCHAR(16)      	NOT NULL,
    AGENCIA            		VARCHAR(4)       	NOT NULL,
    CONTA              		VARCHAR(10)      	NOT NULL,

    PRIMARY KEY (ID_CARTAO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE)
);

CREATE TABLE TB_SERVICO (
    ID_SERVICO         		INT           		NOT NULL,
    VALOR              		DECIMAL(10, 2) 	    NOT NULL,
    NOME_SERVICO       	    VARCHAR(100)  	    NOT NULL,
    DESCRICAO          	    VARCHAR(255),

    PRIMARY KEY (ID_SERVICO)
);

CREATE TABLE TB_PRODUTO_TIPO (
    ID_PRODUTO_TIPO    	INT           		NOT NULL,
    DESCRICAO          	VARCHAR(100),

    PRIMARY KEY (ID_PRODUTO_TIPO)
);

CREATE TABLE TB_PRODUTO (
    ID_PRODUTO         	INT           		NOT NULL,
    ID_PRODUTO_TIPO    	INT           		NOT NULL,
    VALOR              	DECIMAL(10, 2) 	    NOT NULL,
    NOME_PRODUTO       	VARCHAR(100)  	    NOT NULL,
    DESCRICAO          	VARCHAR(255),

    PRIMARY KEY (ID_PRODUTO),
    FOREIGN KEY (ID_PRODUTO_TIPO) REFERENCES TB_PRODUTO_TIPO(ID_PRODUTO_TIPO)
);

CREATE TABLE TB_PACOTE (
    ID_PACOTE          	INT           NOT NULL,
    ID_FORNECEDOR      	INT           NOT NULL,

    PRIMARY KEY (ID_PACOTE)
);

CREATE TABLE TB_PACOTE_PRODUTO (
    ID_PACOTE_PRODUTO  	INT           NOT NULL,
    ID_PRODUTO         	INT           NOT NULL,
    ID_PACOTE          	INT           NOT NULL,
    QUANTIDADE         	INT           NOT NULL,

    PRIMARY KEY (ID_PACOTE_PRODUTO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO),
    FOREIGN KEY (ID_PACOTE) REFERENCES TB_PACOTE(ID_PACOTE)
);

CREATE TABLE TB_CARRINHO (
    ID_CARRINHO        	INT           NOT NULL,
    ID_CLIENTE         	INT           NOT NULL,

    PRIMARY KEY (ID_CARRINHO)
);

CREATE TABLE TB_ENDERECO_TIPO (
    ID_ENDERECO_TIPO   	INT           NOT NULL,
    DESCRICAO          	VARCHAR(100),

    PRIMARY KEY (ID_ENDERECO_TIPO)
);

CREATE TABLE TB_FUNCIONARIO (
    ID_FUNCIONARIO     	INT           		NOT NULL,
    PRIMEIRO_NOME      	VARCHAR(50)   	    NOT NULL,
    ULTIMO_NOME        	VARCHAR(50)   	    NOT NULL,
    CPF                	VARCHAR(11)      	NOT NULL,

    PRIMARY KEY (ID_FUNCIONARIO)
);

CREATE TABLE TB_FORNECEDOR (
    ID_FORNECEDOR      	INT           		NOT NULL,
    ID_USUARIO         	INT           		NOT NULL,
    CNPJ               	VARCHAR(14)     	NOT NULL,
    NOME_EMPRESA       	VARCHAR(100),

    PRIMARY KEY (ID_FORNECEDOR)
);

CREATE TABLE TB_METODO_PAGAMENTO (
    ID_METODO          INT           		NOT NULL,
    NOME               VARCHAR(100),
    DESCRICAO          VARCHAR(255),

    PRIMARY KEY (ID_METODO)
);

CREATE TABLE TB_USUARIO (
    ID_USUARIO         	INT           		NOT NULL,
    EMAIL              	VARCHAR(100)  	    NOT NULL,
    SENHA              	VARCHAR(255)  	    NOT NULL,
    DATA_CRIACAO       	DATE          		NOT NULL,

    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE TB_ENDERECOS (
    ID_ENDERECO        	INT           		NOT NULL,
    ID_ENDERECO_TIPO   	INT           		NOT NULL,
    ID_USUARIO         	INT          		NOT NULL,
    NUMERO             	VARCHAR(10),
    RUA                	VARCHAR(100),
    LOGRADOURO         	VARCHAR(100),
    BAIRRO             	VARCHAR(100),
    CIDADE             	VARCHAR(100),

    PRIMARY KEY (ID_ENDERECO),
    FOREIGN KEY (ID_ENDERECO_TIPO) REFERENCES TB_ENDERECO_TIPO(ID_ENDERECO_TIPO),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
);

CREATE TABLE TB_COMPRA (
    ID_COMPRA          	INT           		NOT NULL,
    ID_METODO          	INT           		NOT NULL,
    ID_CLIENTE         	INT           		NOT NULL,
    ID_ENDERECO        	INT           		NOT NULL,
    MOMENTO_ENTREGA    	TIMESTAMP    	    NOT NULL,
    MOMENTO_COMPRA     	TIMESTAMP     	    NOT NULL,
    VALOR_TOTAL        	DECIMAL(10, 2) 	    NOT NULL,

    PRIMARY KEY (ID_COMPRA),
    FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_METODO) REFERENCES TB_METODO_PAGAMENTO(ID_METODO),
    FOREIGN KEY (ID_ENDERECO) REFERENCES TB_ENDERECOS(ID_ENDERECO)
);

CREATE TABLE TB_PACOTE_COMPRA (
    ID_PACOTE_COMPRA   	INT           NOT NULL,
    ID_PACOTE          	INT           NOT NULL,
    ID_COMPRA          	INT           NOT NULL,

    PRIMARY KEY (ID_PACOTE_COMPRA),
    FOREIGN KEY (ID_COMPRA) REFERENCES TB_COMPRA(ID_COMPRA)
);

CREATE TABLE TB_CONTAS_BANCO (
    ID_CONTA           	INT           		NOT NULL,
    ID_FORNECEDOR      	INT           		NOT NULL,
    BANCO              	VARCHAR(100)  	    NOT NULL,
    AGENCIA            	VARCHAR(4)       	NOT NULL,
    NUM_CONTA          	VARCHAR(10)      	NOT NULL,

    PRIMARY KEY (ID_CONTA),
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES TB_FORNECEDOR(ID_FORNECEDOR)
);

CREATE TABLE TB_CONTRATACAO_TIPO (
    ID_CONTRATO_TIPO   	INT           		NOT NULL,
    DESCRICAO          	VARCHAR(100),

    PRIMARY KEY (ID_CONTRATO_TIPO)
);

CREATE TABLE TB_CONTRATO (
    ID_CONTRATO        	INT           		NOT NULL,
    ID_COMPRA          	INT           		NOT NULL,
    TEXTO_CONTRATO     	VARCHAR2(500),

    PRIMARY KEY (ID_CONTRATO)
);

CREATE TABLE TB_PACOTE_SERVICO (
    ID_PACOTE_SERVICO  	INT           NOT NULL,
    ID_SERVICO         	INT           NOT NULL,
    ID_PACOTE          	INT           NOT NULL,
    QUANTIDADE         	INT           NOT NULL,

    PRIMARY KEY (ID_PACOTE_SERVICO),
    FOREIGN KEY (ID_PACOTE) REFERENCES TB_PACOTE(ID_PACOTE),
    FOREIGN KEY (ID_SERVICO) REFERENCES TB_SERVICO(ID_SERVICO)
);

CREATE TABLE TB_PACOTES_CARRINHO (
    ID_PACOTE_CARRINHO 			INT           	NOT NULL,
    ID_PACOTE          			INT           	NOT NULL,
    ID_CARRINHO        			INT           	NOT NULL,
    SELECIONADO_PARA_COMPRAR 	NUMBER(1),

    PRIMARY KEY (ID_PACOTE_CARRINHO),
    FOREIGN KEY (ID_CARRINHO) REFERENCES TB_CARRINHO(ID_CARRINHO),
    FOREIGN KEY (ID_PACOTE) REFERENCES TB_PACOTE(ID_PACOTE)
);

CREATE TABLE TB_FORNECEDOR_FUNCIONARIO (
    ID_FORNECEDOR      	INT           NOT NULL,
    ID_FUNCIONARIO     	INT           NOT NULL,
    ID_CONTRATO_TIPO   	INT           NOT NULL,

    PRIMARY KEY (ID_FORNECEDOR, ID_FUNCIONARIO, ID_CONTRATO_TIPO),
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES TB_FUNCIONARIO(ID_FUNCIONARIO),
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES TB_FORNECEDOR(ID_FORNECEDOR)
);

CREATE TABLE TB_TELEFONES (
    ID_TELEFONE        	INT           		NOT NULL,
    ID_USUARIO         	INT           		NOT NULL,
    NUMERO_TELEFONE    	VARCHAR(15)   	    NOT NULL,
    DDD                	VARCHAR(2)       	NOT NULL,

    PRIMARY KEY (ID_TELEFONE),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
);

-------------------------------------------------------------------

--CRIAÇÃO DAS SEQUENCES--

CREATE SEQUENCE SQ_CLIENTE;
CREATE SEQUENCE SQ_CARTOES;
CREATE SEQUENCE SQ_SERVICO;
CREATE SEQUENCE SQ_PRODUTO_TIPO;
CREATE SEQUENCE SQ_PRODUTO;
CREATE SEQUENCE SQ_PACOTE;
CREATE SEQUENCE SQ_PACOTE_PRODUTO;
CREATE SEQUENCE SQ_CARRINHO;
CREATE SEQUENCE SQ_ENDERECO_TIPO;
CREATE SEQUENCE SQ_FUNCIONARIO;
CREATE SEQUENCE SQ_FORNECEDOR;
CREATE SEQUENCE SQ_METODO_PAGAMENTO;
CREATE SEQUENCE SQ_USUARIO;
CREATE SEQUENCE SQ_ENDERECOS;
CREATE SEQUENCE SQ_COMPRA;
CREATE SEQUENCE SQ_PACOTE_COMPRA;
CREATE SEQUENCE SQ_CONTAS_BANCO;
CREATE SEQUENCE SQ_CONTRATACAO_TIPO;
CREATE SEQUENCE SQ_CONTRATO;
CREATE SEQUENCE SQ_PACOTE_SERVICO;
CREATE SEQUENCE SQ_PACOTES_CARRINHO;
CREATE SEQUENCE SQ_FORNECEDOR_FUNCIONARIO;
CREATE SEQUENCE SQ_TELEFONES;

-------------------------------------------------------------------

--RESTRIÇÕES--

ALTER TABLE TB_CLIENTE ADD CONSTRAINT CK_SEXO CHECK (SEXO IN ('M', 'F', 'I')); 

-------------------------------------------------------------------

--POVOAMENTO DAS TABELAS--

--USUÁRIO--

--USUÁRIO_CLIENTE--

INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, DATA_CRIACAO) VALUES (SQ_USUARIO.nextval, 'cliente1@email.com', 'senha123', '01.01.2010');
INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, DATA_CRIACAO) VALUES (SQ_USUARIO.nextval, 'cliente2@email.com', 'senha123', '02.01.2010');
INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, DATA_CRIACAO) VALUES (SQ_USUARIO.nextval, 'cliente3@email.com', 'senha123', '03.01.2010');

--USUÁRIO_FORNECEDOR--

INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, DATA_CRIACAO) VALUES (SQ_USUARIO.nextval, 'fornecedor1@email.com', 'senha123', '01.01.2000');
INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, DATA_CRIACAO) VALUES (SQ_USUARIO.nextval, 'fornecedor2@email.com', 'senha123', '02.01.2000');
INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, DATA_CRIACAO) VALUES (SQ_USUARIO.nextval, 'fornecedor3@email.com', 'senha123', '03.01.2000');

--CLIENTE--

INSERT INTO TB_CLIENTE (ID_CLIENTE, ID_USUARIO, PRIMEIRO_NOME, ULTIMO_NOME, CPF, SEXO, DATA_NASCIMENTO) VALUES (SQ_CLIENTE.nextval, 1, 'João', 'Silva', '123.456.789-01', 'M', '15.05.1990');
INSERT INTO TB_CLIENTE (ID_CLIENTE, ID_USUARIO, PRIMEIRO_NOME, ULTIMO_NOME, CPF, SEXO, DATA_NASCIMENTO) VALUES (SQ_CLIENTE.nextval, 2, 'Maria', 'Oliveira', '234.567.890-12', 'F', '22.08.1985');
INSERT INTO TB_CLIENTE (ID_CLIENTE, ID_USUARIO, PRIMEIRO_NOME, ULTIMO_NOME, CPF, SEXO, DATA_NASCIMENTO) VALUES (SQ_CLIENTE.nextval, 3, 'Carlos', 'Santos', '345.678.901-23', 'M', '10.11.1987');

--FORNECEDOR--

INSERT INTO TB_FORNECEDOR (ID_FORNECEDOR, ID_USUARIO, CNPJ, NOME_EMPRESA) VALUES (SQ_FORNECEDOR.nextval, 4, '12.345.678/0001-90', 'Buffet e Eventos Silva Ltda');
INSERT INTO TB_FORNECEDOR (ID_FORNECEDOR, ID_USUARIO, CNPJ, NOME_EMPRESA) VALUES (SQ_FORNECEDOR.nextval, 5, '23.456.789/0001-23', 'Feijoadas Oliveira ME');
INSERT INTO TB_FORNECEDOR (ID_FORNECEDOR, ID_USUARIO, CNPJ, NOME_EMPRESA) VALUES (SQ_FORNECEDOR.nextval, 6, '34.567.890/0001-56', 'Churrascos dos Santos Ltda');

--CARTÕES--

INSERT INTO TB_CARTOES (ID_CARTAO, ID_CLIENTE, NOME_TITULAR, VALIDADE, CVV, NUMERO_CARTAO, AGENCIA, CONTA) VALUES (SQ_CARTOES.nextval, 21, 'João Silva', '31.12.2025', '123', '1234567890123456', '1234', '1234567890');
INSERT INTO TB_CARTOES (ID_CARTAO, ID_CLIENTE, NOME_TITULAR, VALIDADE, CVV, NUMERO_CARTAO, AGENCIA, CONTA) VALUES (SQ_CARTOES.nextval, 22, 'Maria Oliveira', '30.11.2024', '234', '2345678901234567', '2345', '2345678901');
INSERT INTO TB_CARTOES (ID_CARTAO, ID_CLIENTE, NOME_TITULAR, VALIDADE, CVV, NUMERO_CARTAO, AGENCIA, CONTA) VALUES (SQ_CARTOES.nextval, 23, 'Carlos Santos', '29.10.2026', '345', '3456789012345678', '3456', '3456789012');

--TELEFONE--

INSERT INTO TB_TELEFONES (ID_TELEFONE, ID_USUARIO, NUMERO_TELEFONE, DDD) VALUES (SQ_TELEFONES.nextval, 1, 912133445685, 71); 
INSERT INTO TB_TELEFONES (ID_TELEFONE, ID_USUARIO, NUMERO_TELEFONE, DDD) VALUES (SQ_TELEFONES.nextval, 3, 912223445685, 71); 
INSERT INTO TB_TELEFONES (ID_TELEFONE, ID_USUARIO, NUMERO_TELEFONE, DDD) VALUES (SQ_TELEFONES.nextval, 5, 919999999999, 71); 

--CONTAS BANCO--

INSERT INTO TB_CONTAS_BANCO (ID_CONTA, ID_FORNECEDOR, BANCO, AGENCIA, NUM_CONTA) VALUES (SQ_CONTAS_BANCO.nextval, 4, 'Banco do Brasil', '0001', '1234567-8');
INSERT INTO TB_CONTAS_BANCO (ID_CONTA, ID_FORNECEDOR, BANCO, AGENCIA, NUM_CONTA) VALUES (SQ_CONTAS_BANCO.nextval, 5, 'Itaú', '0002', '2345678-9');
INSERT INTO TB_CONTAS_BANCO (ID_CONTA, ID_FORNECEDOR, BANCO, AGENCIA, NUM_CONTA) VALUES (SQ_CONTAS_BANCO.nextval, 6, 'Caixa Econômica', '0003', '3456789-0');
    
--ENDEREÇO_TIPO--

INSERT INTO TB_ENDERECO_TIPO (ID_ENDERECO_TIPO, DESCRICAO) VALUES (SQ_ENDERECO_TIPO.nextval, 'Residencial'); 
INSERT INTO TB_ENDERECO_TIPO (ID_ENDERECO_TIPO, DESCRICAO) VALUES (SQ_ENDERECO_TIPO.nextval, 'Empresarial'); 

--ENDERECO--

INSERT INTO TB_ENDERECOS (ID_ENDERECO, ID_ENDERECO_TIPO, ID_USUARIO, NUMERO, RUA, LOGRADOURO, BAIRRO, CIDADE) VALUES (SQ_ENDERECOS.nextval, 1, 1, '123', 'Rua das Flores', 'Avenida Central', 'Centro', 'São Paulo');
INSERT INTO TB_ENDERECOS (ID_ENDERECO, ID_ENDERECO_TIPO, ID_USUARIO, NUMERO, RUA, LOGRADOURO, BAIRRO, CIDADE) VALUES (SQ_ENDERECOS.nextval, 2, 4, '456', 'Rua dos Lírios', 'Alameda Sul', 'Jardim América', 'Rio de Janeiro');
INSERT INTO TB_ENDERECOS (ID_ENDERECO, ID_ENDERECO_TIPO, ID_USUARIO, NUMERO, RUA, LOGRADOURO, BAIRRO, CIDADE) VALUES (SQ_ENDERECOS.nextval, 1, 2, '789', 'Rua dos Jasmins', 'Rua Principal', 'Bela Vista', 'Belo Horizonte');
INSERT INTO TB_ENDERECOS (ID_ENDERECO, ID_ENDERECO_TIPO, ID_USUARIO, NUMERO, RUA, LOGRADOURO, BAIRRO, CIDADE) VALUES (SQ_ENDERECOS.nextval, 2, 5, '101', 'Avenida das Palmeiras', 'Setor Oeste', 'Vila Nova', 'Curitiba');
INSERT INTO TB_ENDERECOS (ID_ENDERECO, ID_ENDERECO_TIPO, ID_USUARIO, NUMERO, RUA, LOGRADOURO, BAIRRO, CIDADE) VALUES (SQ_ENDERECOS.nextval, 1, 3, '202', 'Rua dos Cravos', 'Avenida Norte', 'Centro', 'Porto Alegre');

--FUNCIONARIO--

INSERT INTO TB_FUNCIONARIO (ID_FUNCIONARIO, PRIMEIRO_NOME, ULTIMO_NOME, CPF) VALUES (SQ_FUNCIONARIO.nextval, 'CARLOS', 'ALBERTO','111.111.111-11'); 
INSERT INTO TB_FUNCIONARIO (ID_FUNCIONARIO, PRIMEIRO_NOME, ULTIMO_NOME, CPF) VALUES (SQ_FUNCIONARIO.nextval, 'ROBERTO', 'CARLOS', '222.222.222-22'); 

--CONTRATACAO_TIPO--

INSERT INTO TB_CONTRATACAO_TIPO (ID_CONTRATO_TIPO, DESCRICAO) VALUES (SQ_CONTRATACAO_TIPO.nextval, 'PJ');
INSERT INTO TB_CONTRATACAO_TIPO (ID_CONTRATO_TIPO, DESCRICAO) VALUES (SQ_CONTRATACAO_TIPO.nextval, 'CLT');

--SERVICO--

INSERT INTO TB_SERVICO (ID_SERVICO, VALOR, NOME_SERVICO, DESCRICAO) VALUES (SQ_SERVICO.nextval, 150.00, 'Garçom', 'Serviço de garçom para eventos');
INSERT INTO TB_SERVICO (ID_SERVICO, VALOR, NOME_SERVICO, DESCRICAO) VALUES (SQ_SERVICO.nextval, 200.00, 'Mesa de Roska', 'Mesa de roska completa');
INSERT INTO TB_SERVICO (ID_SERVICO, VALOR, NOME_SERVICO, DESCRICAO) VALUES (SQ_SERVICO.nextval, 100.00, 'Música ao Vivo', 'Banda de música ao vivo para festas');

--PRODUTO_TIPO--

INSERT INTO TB_PRODUTO_TIPO (ID_PRODUTO_TIPO, DESCRICAO) VALUES (SQ_PRODUTO_TIPO.nextval, 'Salgados');   
INSERT INTO TB_PRODUTO_TIPO (ID_PRODUTO_TIPO, DESCRICAO) VALUES (SQ_PRODUTO_TIPO.nextval, 'Doces');
INSERT INTO TB_PRODUTO_TIPO (ID_PRODUTO_TIPO, DESCRICAO) VALUES (SQ_PRODUTO_TIPO.nextval, 'Comida'); 

--PRODUTO--

INSERT INTO TB_PRODUTO (ID_PRODUTO, ID_PRODUTO_TIPO, VALOR, NOME_PRODUTO, DESCRICAO) VALUES (SQ_PRODUTO.nextval, 2, 2.00, 'Brigadeiro', 'Brigadeiro clássico');  
INSERT INTO TB_PRODUTO (ID_PRODUTO, ID_PRODUTO_TIPO, VALOR, NOME_PRODUTO, DESCRICAO) VALUES (SQ_PRODUTO.nextval, 1, 1500.00, 'Feijoada', 'Feijoada completa');
INSERT INTO TB_PRODUTO (ID_PRODUTO, ID_PRODUTO_TIPO, VALOR, NOME_PRODUTO, DESCRICAO) VALUES (SQ_PRODUTO.nextval, 3, 3.00, 'Coxinha', 'Coxinha de frango');

--PACOTE--

INSERT INTO TB_PACOTE (ID_PACOTE, ID_FORNECEDOR) VALUES (SQ_PACOTE.nextval, 4); 
INSERT INTO TB_PACOTE (ID_PACOTE, ID_FORNECEDOR) VALUES (SQ_PACOTE.nextval, 5); 
INSERT INTO TB_PACOTE (ID_PACOTE, ID_FORNECEDOR) VALUES (SQ_PACOTE.nextval, 6); 

--PACOTE_PRODUTO--

INSERT INTO TB_PACOTE_PRODUTO (ID_PACOTE_PRODUTO, ID_PACOTE, ID_PRODUTO, QUANTIDADE) VALUES (SQ_PACOTE_PRODUTO.NEXTVAL, 1, 1, 1);
INSERT INTO TB_PACOTE_PRODUTO (ID_PACOTE_PRODUTO, ID_PACOTE, ID_PRODUTO, QUANTIDADE) VALUES (SQ_PACOTE_PRODUTO.NEXTVAL, 2, 2, 2);
INSERT INTO TB_PACOTE_PRODUTO (ID_PACOTE_PRODUTO, ID_PACOTE, ID_PRODUTO, QUANTIDADE) VALUES (SQ_PACOTE_PRODUTO.NEXTVAL, 3, 3, 10);

--CARRINHO--

INSERT INTO TB_CARRINHO (ID_CARRINHO, ID_CLIENTE) VALUES (SQ_CARRINHO.nextval, 21); 
INSERT INTO TB_CARRINHO (ID_CARRINHO, ID_CLIENTE) VALUES (SQ_CARRINHO.nextval, 22);
INSERT INTO TB_CARRINHO (ID_CARRINHO, ID_CLIENTE) VALUES (SQ_CARRINHO.nextval, 23);

--MÉTODO_PAGAMENTO-

INSERT INTO TB_METODO_PAGAMENTO (ID_METODO, NOME, DESCRICAO) VALUES (SQ_METODO_PAGAMENTO.nextval, 'PIX', 'Gera um código copia e cola junto com um QRcode');
INSERT INTO TB_METODO_PAGAMENTO (ID_METODO, NOME, DESCRICAO) VALUES (SQ_METODO_PAGAMENTO.nextval, 'Cartão', 'Cartão de débito ou crédito');
INSERT INTO TB_METODO_PAGAMENTO (ID_METODO, NOME, DESCRICAO) VALUES (SQ_METODO_PAGAMENTO.nextval, 'Boleto', 'Gera um código de barras para pagamento');

--COMPRA--

INSERT INTO TB_COMPRA (ID_COMPRA, ID_METODO, ID_CLIENTE, ID_ENDERECO, MOMENTO_ENTREGA, MOMENTO_COMPRA) VALUES (SQ_COMPRA.NEXTVAL, 3, 21, 2, SYSDATE, SYSDATE);

--PACOTE_COMPRA--

INSERT INTO TB_PACOTE_COMPRA (ID_PACOTE_COMPRA, ID_PACOTE, ID_COMPRA) VALUES (SQ_PACOTE_COMPRA.nextval, 2, 2);

--CONTRATO--

INSERT INTO TB_CONTRATO (ID_CONTRATO, ID_COMPRA, TEXTO_CONTRATO) VALUES (SQ_CONTRATO.nextval, 2, 'teste'); 

--FORNCEDOR_FUNCIONARIO--

INSERT INTO TB_FORNECEDOR_FUNCIONARIO (ID_FORNECEDOR, ID_FUNCIONARIO, ID_CONTRATO_TIPO) VALUES (4, 1, 1); 

--PACOTE_SERVIÇO--

INSERT INTO TB_PACOTE_SERVICO (ID_PACOTE_SERVICO, ID_SERVICO, ID_PACOTE, QUANTIDADE) VALUES (SQ_PACOTE_SERVICO.nextval, 1, 2, 1); 

--PACOTE_CARRINHO--

INSERT INTO TB_PACOTES_CARRINHO (ID_PACOTE_CARRINHO, ID_PACOTE, ID_CARRINHO, SELECIONADO_PARA_COMPRAR) VALUES (SQ_PACOTES_CARRINHO.nextval, 2, 1, 1); 
